[workspace]
members = ["rookie-rs", "bindings/python", "bindings/node", "cli", "xtask"]

exclude = ["examples/rust/http"]

default-members = ["rookie-rs", "bindings/python"]
resolver = "2"

[workspace.package]
version = "0.6.0-beta.2"

[workspace.dependencies.rookie-cookies]
path = "rookie-rs"
version = "0.6.0-beta.2"
default-features = false

[profile.release]
lto = true
strip = "symbols"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
