use crate::enums::{Cookie, DetailedCookie};

pub fn json(cookies: Vec<Cookie>) -> String {
  serde_json::to_string_pretty(&cookies).expect("cannot convert cookies to json")
}

/// Serializes cookies with their partition/container context.
///
/// Without this, isolation would exist on the CLI only as an invisible side
/// effect of `header` matching, and an operator could not inventory CHIPS
/// partitions or Firefox containers from the surface most likely to be used
/// for exactly that. [`json`] and [`netscape`] stay eight-field projections
/// because neither format can represent a partition.
pub fn detailed_json(cookies: Vec<DetailedCookie>) -> String {
  serde_json::to_string_pretty(&cookies).expect("cannot convert detailed cookies to json")
}

/// Serialize cookies in the seven-column Netscape cookie-file format.
///
/// Tabs, carriage returns, and line feeds in cookie-controlled fields are
/// percent-encoded. Hash signs are encoded only in the domain field, where a
/// literal leading `#` would turn a cookie into a comment or a forged
/// `#HttpOnly_` marker in standard Netscape-file parsers.
pub fn netscape(cookies: Vec<Cookie>) -> String {
  let mut data = indoc::formatdoc! {"
    # Netscape HTTP Cookie File
    # Generated by rookie-cookies {}
    # Edit at your own risk.\n
  ", crate::version()}
  .to_string();
  for cookie in cookies {
    let subdomain = cookie.domain.starts_with('.').to_string().to_uppercase();
    let domain = escape_netscape_domain(&cookie.domain);
    let domain = if cookie.http_only {
      format!("#HttpOnly_{domain}")
    } else {
      domain
    };
    let https_only = cookie.secure.to_string().to_uppercase();
    let expires = cookie.expires.unwrap_or(0).to_string();
    data.push_str(&format!(
      "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
      domain,
      subdomain,
      escape_netscape_field(&cookie.path),
      https_only,
      escape_netscape_field(&expires),
      escape_netscape_field(&cookie.name),
      escape_netscape_field(&cookie.value)
    ));
  }
  data
}

fn escape_netscape_field(field: &str) -> String {
  field
    .replace('\t', "%09")
    .replace('\r', "%0D")
    .replace('\n', "%0A")
}

fn escape_netscape_domain(domain: &str) -> String {
  escape_netscape_field(domain).replace('#', "%23")
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn detailed_json_carries_the_context_beside_the_eight_fields() {
    let rendered = detailed_json(vec![DetailedCookie {
      cookie: Cookie {
        domain: ".example.com".to_owned(),
        path: "/".to_owned(),
        secure: true,
        expires: None,
        name: "chips".to_owned(),
        value: "value".to_owned(),
        http_only: false,
        same_site: 0,
      },
      context: crate::enums::CookieContext {
        top_frame_site_key: Some("https://top.example".to_owned()),
        ..crate::enums::CookieContext::default()
      },
    }]);
    let parsed: serde_json::Value = serde_json::from_str(&rendered).expect("valid JSON");
    assert_eq!(parsed[0]["cookie"]["name"], "chips");
    assert_eq!(
      parsed[0]["context"]["top_frame_site_key"],
      "https://top.example"
    );
    assert!(parsed[0]["context"]["partition_key"].is_null());
  }

  #[test]
  fn test_netscape_formatting() {
    let cookies = vec![
      Cookie {
        domain: ".example.com".to_string(),
        path: "/".to_string(),
        secure: true,
        expires: Some(1700000000),
        name: "session".to_string(),
        value: "abc".to_string(),
        http_only: true,
        same_site: 0,
      },
      Cookie {
        domain: "example.com".to_string(),
        path: "/api".to_string(),
        secure: false,
        expires: None,
        name: "test".to_string(),
        value: "123".to_string(),
        http_only: false,
        same_site: 0,
      },
    ];

    let output = netscape(cookies);
    let expected_header = format!(
      "# Netscape HTTP Cookie File\n# Generated by rookie-cookies {}\n# Edit at your own risk.\n\n",
      crate::version()
    );
    let expected_line1 = "#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1700000000\tsession\tabc\n";
    let expected_line2 = "example.com\tFALSE\t/api\tFALSE\t0\ttest\t123\n";
    let expected = format!("{}{}{}", expected_header, expected_line1, expected_line2);

    assert_eq!(output, expected);
  }

  #[test]
  fn netscape_escapes_record_and_field_separators() {
    let output = netscape(vec![Cookie {
      domain: "#HttpOnly_.exa\tmple\r.test".to_string(),
      path: "/line\npath".to_string(),
      secure: false,
      expires: None,
      name: "na\tme".to_string(),
      value: "safe\n.evil.test\tTRUE\t/\tTRUE\t1\tforged\tvalue\r".to_string(),
      http_only: true,
      same_site: 0,
    }]);

    assert_eq!(
      output,
      format!(
        "# Netscape HTTP Cookie File\n\
         # Generated by rookie-cookies {}\n\
         # Edit at your own risk.\n\n\
         #HttpOnly_%23HttpOnly_.exa%09mple%0D.test\tFALSE\t/line%0Apath\tFALSE\t0\tna%09me\tsafe%0A.evil.test%09TRUE%09/%09TRUE%091%09forged%09value%0D\n",
        crate::version()
      )
    );
    assert_eq!(output.lines().count(), 5);
  }

  #[test]
  fn netscape_neutralizes_comment_and_httponly_marker_forgery() {
    for domain in ["#comment.test", "#HttpOnly_victim.test"] {
      let output = netscape(vec![Cookie {
        domain: domain.to_owned(),
        path: "/".to_owned(),
        secure: false,
        expires: None,
        name: "session".to_owned(),
        value: "value".to_owned(),
        http_only: false,
        same_site: 0,
      }]);
      let record = output.lines().last().expect("cookie record");
      assert!(record.starts_with("%23"), "unescaped record: {record}");
      assert!(
        !record.starts_with('#'),
        "record became a comment: {record}"
      );
    }
  }

  #[test]
  fn netscape_preserves_literal_hashes_outside_the_domain_column() {
    let output = netscape(vec![Cookie {
      domain: "example.com".to_owned(),
      path: "/fragment#anchor".to_owned(),
      secure: false,
      expires: None,
      name: "name#suffix".to_owned(),
      value: "value#fragment".to_owned(),
      http_only: false,
      same_site: 0,
    }]);

    let record = output.lines().last().expect("cookie record");
    assert_eq!(
      record,
      "example.com\tFALSE\t/fragment#anchor\tFALSE\t0\tname#suffix\tvalue#fragment"
    );
  }
}
