[package]
name = "rookie-cookies-cli"
version = "0.5.7"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
lazy_static = "1.4.0"
rookie-cookies = { path = "../rookie-rs", version = "0.5.7" }
serde_json = "1.0.107"

[dev-dependencies]
rusqlite = { version = "0.31", features = ["bundled"] }

[features]
appbound = ["rookie-cookies/appbound"]

[[bin]]
name = "rookie-cookies"
path = "src/main.rs"
