[package]
name = "rookie-cookies-python"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rookie_cookies"
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
pyo3 = { version = "0.29", features = ["abi3-py311", "anyhow"] }
pyo3-log = "0.13"

[target.'cfg(windows)'.dependencies]
rookie-cookies = { workspace = true, features = ["appbound"] }

[target.'cfg(unix)'.dependencies]
rookie-cookies.workspace = true
