[package]
edition = "2021"
name = "rookie-cookies-node"
version = "0.5.8"

[lib]
crate-type = ["cdylib"]

[features]
test-support = []

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4", "async"] }
napi-derive = "2.12.2"
tokio = { version = "1", features = ["rt-multi-thread"] }


[target.'cfg(windows)'.dependencies]
rookie-cookies = { path = "../../rookie-rs", version = "0.5.8", features = [
  "appbound",
] }

[target.'cfg(unix)'.dependencies]
rookie-cookies = { path = "../../rookie-rs", version = "0.5.8" }

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
