/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process
const { optionalDependencies = {} } = require('./package.json')

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'rookie_cookies.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.android-arm64.node')
          } else {
            nativeBinding = require('rookie-cookies-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'rookie_cookies.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.android-arm-eabi.node')
          } else {
            nativeBinding = require('rookie-cookies-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.win32-x64-msvc.node')
          } else {
            nativeBinding = require('rookie-cookies-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('rookie-cookies-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('rookie-cookies-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'rookie_cookies.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./rookie_cookies.darwin-universal.node')
      } else {
        nativeBinding = require('rookie-cookies-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'rookie_cookies.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.darwin-x64.node')
          } else {
            nativeBinding = require('rookie-cookies-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.darwin-arm64.node')
          } else {
            nativeBinding = require('rookie-cookies-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'rookie_cookies.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./rookie_cookies.freebsd-x64.node')
      } else {
        nativeBinding = require('rookie-cookies-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-x64-musl.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-x64-gnu.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm64-musl.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('rookie-cookies-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError && loadError.code === 'MODULE_NOT_FOUND') {
    const missingPackage = loadError.message.match(
      /['"](rookie-cookies-[^'"]+)['"]/
    )
    if (
      missingPackage &&
      !Object.prototype.hasOwnProperty.call(optionalDependencies, missingPackage[1])
    ) {
      throw new Error(
        `No prebuilt rookie-cookies binding is published for ${platform}-${arch}; build the Node binding from source or use a supported platform`
      )
    }
  }
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { version, toNetscape, anyBrowser, firefox, firefoxProfiles, firefoxProfile, zen, librewolf, chrome, brave, arc, edge, opera, operaGx, chromium, vivaldi, firefoxBased, load, octoBrowser, internetExplorer, safari, chromiumBased, testWorkerPanic } = nativeBinding

function requiredNative(nativeFunction, name) {
  if (typeof nativeFunction !== 'function') {
    throw new TypeError(`Expected a native binding function: ${name}`)
  }
  return nativeFunction
}

function asyncNative(nativeFunction, name) {
  requiredNative(nativeFunction, name)
  return (...args) => {
    try {
      return Promise.resolve(nativeFunction(...args))
    } catch (error) {
      return Promise.reject(error)
    }
  }
}

function unsupportedPlatform(name, supportedPlatform) {
  return () => Promise.reject(new Error(
    `${name} is only available on ${supportedPlatform}; current platform is ${platform}`
  ))
}

function platformNative(nativeFunction, name, nodePlatform, supportedPlatform) {
  if (typeof nativeFunction === 'function') {
    return asyncNative(nativeFunction, name)
  }
  if (platform === nodePlatform) {
    requiredNative(nativeFunction, name)
  }
  return asyncNative(unsupportedPlatform(name, supportedPlatform), name)
}

module.exports.version = requiredNative(version, 'version')
module.exports.toNetscape = requiredNative(toNetscape, 'toNetscape')
module.exports.anyBrowser = asyncNative(anyBrowser, 'anyBrowser')
module.exports.firefox = asyncNative(firefox, 'firefox')
module.exports.zen = asyncNative(zen, 'zen')
module.exports.librewolf = asyncNative(librewolf, 'librewolf')
module.exports.chrome = asyncNative(chrome, 'chrome')
module.exports.brave = asyncNative(brave, 'brave')
module.exports.arc = asyncNative(arc, 'arc')
module.exports.edge = asyncNative(edge, 'edge')
module.exports.opera = asyncNative(opera, 'opera')
module.exports.operaGx = asyncNative(operaGx, 'operaGx')
module.exports.chromium = asyncNative(chromium, 'chromium')
module.exports.vivaldi = asyncNative(vivaldi, 'vivaldi')
module.exports.load = asyncNative(load, 'load')
module.exports.octoBrowser = platformNative(octoBrowser, 'octoBrowser', 'win32', 'Windows')
module.exports.internetExplorer = platformNative(internetExplorer, 'internetExplorer', 'win32', 'Windows')
module.exports.safari = platformNative(safari, 'safari', 'darwin', 'macOS')
module.exports.chromiumBased = asyncNative(chromiumBased, 'chromiumBased')
module.exports.firefoxProfiles = asyncNative(firefoxProfiles, 'firefoxProfiles')
module.exports.firefoxProfile = asyncNative(firefoxProfile, 'firefoxProfile')
module.exports.firefoxBased = asyncNative(firefoxBased, 'firefoxBased')

if (testWorkerPanic) {
  module.exports.__testWorkerPanic = asyncNative(testWorkerPanic, 'testWorkerPanic')
}
