/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process
const { optionalDependencies = {} } = require('./package.json')

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'rookie_cookies.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.android-arm64.node')
          } else {
            nativeBinding = require('rookie-cookies-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'rookie_cookies.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.android-arm-eabi.node')
          } else {
            nativeBinding = require('rookie-cookies-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.win32-x64-msvc.node')
          } else {
            nativeBinding = require('rookie-cookies-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('rookie-cookies-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('rookie-cookies-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'rookie_cookies.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./rookie_cookies.darwin-universal.node')
      } else {
        nativeBinding = require('rookie-cookies-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'rookie_cookies.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.darwin-x64.node')
          } else {
            nativeBinding = require('rookie-cookies-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.darwin-arm64.node')
          } else {
            nativeBinding = require('rookie-cookies-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'rookie_cookies.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./rookie_cookies.freebsd-x64.node')
      } else {
        nativeBinding = require('rookie-cookies-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-x64-musl.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-x64-gnu.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm64-musl.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rookie_cookies.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rookie_cookies.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('rookie-cookies-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'rookie_cookies.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rookie_cookies.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('rookie-cookies-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError && loadError.code === 'MODULE_NOT_FOUND') {
    const missingPackage = loadError.message.match(
      /['"](rookie-cookies-[^'"]+)['"]/
    )
    if (
      missingPackage &&
      !Object.prototype.hasOwnProperty.call(optionalDependencies, missingPackage[1])
    ) {
      throw new Error(
        `No prebuilt rookie-cookies binding is published for ${platform}-${arch}; build the Node binding from source or use a supported platform`
      )
    }
  }
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { version, anyBrowser, firefox, zen, librewolf, chrome, brave, arc, edge, opera, operaGx, chromium, vivaldi, firefoxBased, load, octoBrowser, internetExplorer, safari, chromiumBased } = nativeBinding

function unsupportedPlatform(name, supportedPlatform) {
  return () => Promise.reject(new Error(
    `${name} is only available on ${supportedPlatform}; current platform is ${platform}`
  ))
}

module.exports.version = version
module.exports.anyBrowser = anyBrowser
module.exports.firefox = firefox
module.exports.zen = zen
module.exports.librewolf = librewolf
module.exports.chrome = chrome
module.exports.brave = brave
module.exports.arc = arc
module.exports.edge = edge
module.exports.opera = opera
module.exports.operaGx = operaGx
module.exports.chromium = chromium
module.exports.vivaldi = vivaldi
module.exports.load = load
module.exports.octoBrowser = octoBrowser || unsupportedPlatform('octoBrowser', 'Windows')
module.exports.internetExplorer = internetExplorer || unsupportedPlatform('internetExplorer', 'Windows')
module.exports.safari = safari || unsupportedPlatform('safari', 'macOS')
module.exports.chromiumBased = chromiumBased
module.exports.firefoxBased = firefoxBased
