name: Lint rookie-cookies

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rustfmt.toml"
      - "rookie-rs/**"
      - "cli/**/*.rs"
      - "cli/Cargo.toml"
      - "bindings/python/src/**/*.rs"
      - "bindings/python/Cargo.toml"
      - "bindings/node/src/**/*.rs"
      - "bindings/node/build.rs"
      - "bindings/node/Cargo.toml"
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable and rustfmt
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --manifest-path Cargo.toml --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable and clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: .

      - name: run Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Verify cargo package
        run: |
          cargo package --manifest-path Cargo.toml -p rookie-cookies --locked --list > package_files.txt
          cat package_files.txt
          grep -q "^examples/simple.rs$" package_files.txt
          grep -q "^examples/from_path.rs$" package_files.txt
